type Strings = Record<string, string>;

const STRINGS: Strings = {
  achievementActiveDesc: "Sakupi 500 poena",
  achievementActiveTitle: "Aktivan \u010dlan",
  achievementBeginnerDesc: "Sakupi 100 poena",
  achievementBeginnerTitle: "Po\u010detnik",
  achievementFighterDesc: "Sakupi 1000 poena",
  achievementFighterTitle: "Eko borac",
  achievementHeroDesc: "Sakupi 2500 poena",
  achievementHeroTitle: "Eko heroj",
  achievementLegendDesc: "Sakupi 5000 poena",
  achievementLegendTitle: "Legenda prirode",
  adminModerationDesc: "Odobri ili odbij foto i grupne prijave",
  adminModerationLabel: "Moderacija prijava",
  adminSection: "Administracija",
  appSubtitle: "\u010cuvaj prirodu.",
  appTitle: "GrowWithUs",
  backLabel: "Nazad",
  badgeBronze: "Bronze",
  badgeGold: "Gold",
  badgeSilver: "Silver",
  brandName: "GrowWithUs",
  cacheNote: "Prikazujem ke\u0161irane podatke.",
  communityFilterAll: "Svi",
  communityFilterBronze: "Bronze",
  communityFilterGold: "Gold",
  communityFilterSilver: "Silver",
  communityLoadError: "Gre\u0161ka pri u\u010ditavanju rang liste.",
  communityLoadMore: "Prika\u017ei vi\u0161e",
  communitySearchPlaceholder: "Pretra\u017ei korisnike...",
  communitySubtitle: "Top rang lista i bed\u017eevi",
  communityTitle: "Zajednica",
  contactTitle: "Kontakt i podr\u0161ka",
  copyrightLabel: "\u00a9 2025 GrowWithUs Nenad",
  daysLabel: "dana",
  errorTitle: "Gre\u0161ka",
  friendsChatLabel: "Chat",
  friendsEmptyDesc: "Pove\u017eite se sa zajednicom i pratite napredak.",
  friendsEmptyTitle: "Jo\u0161 nemate prijatelja",
  friendsGroupsLoadError: "Ne mo\u017eemo u\u010ditati grupe.",
  friendsJoinGroupError: "Ne mo\u017eemo se pridru\u017eiti grupi.",
  friendsJoinGroupSuccess: "Pridru\u017eili ste se grupi.",
  friendsLoadError: "Gre\u0161ka pri u\u010ditavanju prijatelja.",
  friendsLoadErrorToast: "Ne mogu u\u010ditati prijatelje.",
  friendsPointsPrefix: "Poeni",
  friendsRemoveError: "Ne mo\u017eemo ukloniti prijatelja.",
  friendsRemoveLabel: "Ukloni",
  friendsRemoveSuccess: "Prijatelj je uklonjen.",
  friendsRequestAcceptError: "Ne mo\u017eemo prihvatiti zahtjev.",
  friendsRequestAcceptSuccess: "Zahtjev je prihva\u0107en.",
  friendsRequestSendError: "Ne mo\u017eemo poslati zahtjev.",
  friendsRequestSendSuccess: "Zahtjev je poslat.",
  friendsSearchFriendsPlaceholder: "Pretra\u017ei prijatelje...",
  friendsSearchUsersPlaceholder: "Pretra\u017ei korisnike...",
  friendsSubtitle: "Pove\u017ei se s eko zajednicom",
  friendsTabFriends: "Prijatelji",
  friendsTabGroups: "Grupe",
  friendsTabRequests: "Zahtjevi",
  friendsTabUsers: "Korisnici",
  friendsTitle: "Prijatelji",
  groupsCreateLabel: "Kreiraj grupu",
  groupsJoinLabel: "Pridru\u017ei se",
  groupsMyEmptyDesc: "Pridru\u017eite se grupi i pratite zajedni\u010dke izazove.",
  groupsMyEmptyTitle: "Niste \u010dlan nijedne grupe",
  groupsMyTitle: "Moje grupe",
  groupsOpenLabel: "Otvori",
  groupsRecommendedEmptyDesc: "Vrati se kasnije za nove preporuke.",
  groupsRecommendedEmptyTitle: "Trenutno nema preporu\u010denih grupa",
  groupsRecommendedTitle: "Preporu\u010dene grupe",
  hideConfirmPasswordLabel: "Sakrij potvrdu lozinke",
  hidePasswordLabel: "Sakrij lozinku",
  homeBadgeLabel: "Bed\u017e",
  homeCommunity: "Zajednica",
  homeCommunitySubtitle: "Rang lista",
  homeDailyChallenges: "Dnevni Izazovi",
  homeEcoTips: "Eko savjeti",
  homeEcoTipsSubtitle: "Saznaj vi\u0161e",
  homeNoActivities: "Jo\u0161 nema aktivnosti.",
  homeQuickActions: "Brze akcije",
  homeRecentActivities: "Nedavne aktivnosti",
  homeStreakLabel: "Dnevna serija",
  homeTotalPointsLabel: "Ukupni poeni",
  homeWelcomePrefix: "Dobro do\u0161ao nazad,",
  languageDesc: "Srpski / Engleski",
  languageLabel: "Jezik",
  languageOptionEn: "Engleski",
  languageOptionSr: "Srpski",
  languageScreenSubtitle: "Izaberite jezik aplikacije",
  languageScreenTitle: "Jezik",
  languageSection: "Jezik i region",
  levelActive: "Aktivan \u010dlan",
  levelBeginner: "Po\u010detnik",
  levelFighter: "Eko borac",
  levelHero: "Eko heroj",
  levelLegend: "Legenda prirode",
  levelRookie: "Rookie",
  loadMoreLabel: "Prika\u017ei vi\u0161e",
  loadingLabel: "U\u010ditavanje...",
  loginBackToLogin: "Nazad na prijavu",
  loginButton: "Prijavi se",
  loginEmailLabel: "Email",
  loginForgot: "Zaboravljena lozinka?",
  loginMissingFields: "Unesite email i lozinku",
  loginNoAccount: "Nemate nalog? Registrujte se",
  loginPasswordLabel: "Lozinka",
  loginResetButton: "Po\u0161alji link",
  loginResetMissingEmail: "Unesite email adresu",
  loginResetSentMessage: "Provjerite email za reset lozinke.",
  loginResetSubtitle: "Unesite email adresu i posla\u0107emo vam link za reset.",
  loginResetTitle: "Reset lozinke",
  loginSuccessMessage: "Prijava uspje\u0161na.",
  loginTitle: "Dobrodo\u0161li nazad",
  notificationsDesc: "Primaj obavje\u0161tenja o novim izazovima",
  notificationsLabel: "Push obavje\u0161tenja",
  notificationsSection: "Obavje\u0161tenja",
  pointsLabel: "poena",
  privacyBody1: "Va\u0161e osnovne informacije koristimo isklju\u010divo za funkcionisanje aplikacije (profil, poeni, rang).",
  privacyBody2: "Fotografije izazova se \u010duvaju radi provjere i dodjele poena. Ne dijelimo ih sa tre\u0107im stranama.",
  privacyBody3: "U pode\u0161avanjima telefona mo\u017eete upravljati dozvolama za kameru i obavje\u0161tenja.",
  privacyDesc: "Upravljaj pristupom aplikaciji",
  privacyLabel: "Privatnost i dozvole",
  privacySection: "Privatnost i bezbjednost",
  privacyTitle: "Privatnost i dozvole",
  profileAchievementsTitle: "Dostignu\u0107a",
  profileActivitiesTitle: "Nedavne aktivnosti",
  profileEditLabel: "Uredi profil",
  profileLoggingOut: "Odjava...",
  profileLogout: "Odjavi se",
  profileNoActivities: "Jo\u0161 nema aktivnosti.",
  profileStatsLabel: "Statistika",
  profileStatsTitle: "Tvoja statistika",
  recentLabel: "Nedavno",
  registerButton: "Registruj se",
  registerConfirmPasswordLabel: "Potvrda lozinke",
  registerEmailLabel: "Email",
  registerEmailPlaceholder: "youremail@example.com",
  registerHaveAccount: "Ve\u0107 imate nalog? Prijavite se",
  registerMissingFields: "Popunite email i lozinku",
  registerNameLabel: "Ime",
  registerNamePlaceholder: "Va\u0161e ime",
  registerPasswordLabel: "Lozinka",
  registerPasswordMismatch: "Lozinke se ne poklapaju",
  registerSuccessMessage: "Proverite email za potvrdu naloga.",
  registerTermsRequired: "Morate prihvatiti uslove kori\u0161\u0107enja",
  registerTermsText: "Prihvatam uslove kori\u0161\u0107enja",
  registerTitle: "Kreiraj nalog",
  requestAcceptLabel: "Prihvati",
  requestIncomingLabel: "Primljen zahtjev",
  requestPendingLabel: "Poslan zahtjev (na \u010dekanju)",
  requestsEmptyDesc: "Novi zahtjevi \u0107e se pojaviti ovdje.",
  requestsEmptyTitle: "Nema aktivnih zahtjeva",
  sentTitle: "Poslato",
  settingsSubtitle: "Prilagodi svoju aplikaciju",
  settingsTitle: "Pode\u0161avanja",
  showConfirmPasswordLabel: "Prika\u017ei potvrdu lozinke",
  showPasswordLabel: "Prika\u017ei lozinku",
  statChallengesCompleted: "Izazova zavr\u0161eno",
  statDailyStreak: "Dnevna serija",
  statTotalPoints: "Ukupno poena",
  successTitle: "Uspjeh",
  tabChallenges: "Izazovi",
  tabHome: "Po\u010detna",
  tabProfile: "Nalog",
  tabSettings: "Pode\u0161avanja",
  tabStats: "Statistika",
  termsBody1: "Kori\u0161\u0107enjem aplikacije pristajete na prikupljanje osnovnih podataka za nagrade, rangiranje i aktivnosti.",
  termsBody2: "Va\u0161e fotografije izazova podlije\u017eu provjeri prije dodjele poena. Dijelite autenti\u010dne aktivnosti.",
  termsDesc: "Pro\u010ditaj pravila kori\u0161\u0107enja",
  termsLabel: "Uslovi kori\u0161\u0107enja",
  termsTitle: "Uslovi kori\u0161\u0107enja",
  usersAddLabel: "Dodaj",
  usersEmptyDesc: "Poku\u0161ajte drugi upit za pretragu.",
  usersEmptyTitle: "Nema korisnika",
  versionLabel: "Verzija 1.0.0",
};

export const t = (key: string) => STRINGS[key] ?? key;

export const useLanguage = () => ({ t });
